name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: make init
      - run: make lint
      - run: make typecheck
      - run: make check-with-coverage
