name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.12"

      - run: make init
      - run: make lint
      - run: make typecheck
      - run: make check-with-coverage

      - run: uv build

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
